apiVersion: batch/v1
kind: Job
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: training-container
          image: docker.io/kubeflowkatib/simple-pbt:latest
          imagePullPolicy: Always
          command:
            - "python3"
            - "/opt/pbt/pbt_test.py"
            - "--epochs=20"
            - "--lr=${trialParameters.learningRate}"
            - "--checkpoint=/var/log/katib/checkpoints/"
      restartPolicy: Never
